config/routes.rb
Readathon::Application.routes.draw do
  root "pages#index"
  
  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title, :pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :find_book, only: [:show, :edit, :update, :destroy]
  
  def index
    @books = Book.all
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new book_params
    if @book.save
      flash[:notice] = "Book successfully created."
      redirect_to @book
    else
      render "new"
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @book.update_attributes book_params
      flash[:notice] = "Book successfully updated."
      redirect_to @book
    else
      render "edit"
    end
  end
  
  def destroy
    if @book.destroy
      flash[:notice] = "Book successfully deleted."
    end
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :pages)
  end
  
  def find_book
    @book = Book.find params[:id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :pages %>

  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<%= render partial: "form" %>

app/views/books/index.html.erb
<%= link_to "Add book", new_book_path %>

<% @books.each do | book | %>
  <%= div_for book do %>
    <%= link_to book.title, book %>
  <% end %>
<% end %>

app/views/books/new.html.erb
<%= render partial: "form" %>

app/views/books/show.html.erb
<%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to "Delete", book_path(@book), method: :delete, data:{confirm: "Are you sure?"} %>

<h1><%= @book.title %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readathon App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Books", books_path %>
  
  <% flash.each do | name, message | %>
  <div class="flash <%= name %>"><%= message %></div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Welcome</h1>